ContestantSystem/ContestantSystem.Web/Controllers/ContestantRatingController.cs
using ContestantSystem.Domain;
using ContestantSystem.Service.Contestant;
using ContestantSystem.Service.ContestantRating;
using ContestantSystem.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContestantSystem.Web.Controllers
{
    public class ContestantRatingController : Controller
    {
        private readonly IContestantRatingService _Service;
        private readonly IContestantService _ContestantService;

        public ContestantRatingController()
        {
            _Service = new ContestantRatingService();
            _ContestantService = new ContestantService();
        }


        private IEnumerable<ContestantRating_VM> GetAverageRating(DateTime? Datefrom, DateTime? Dateto, bool FilterOperation)
        {

            List<ContestantRating_VM> Returnlist = new List<ContestantRating_VM>();


            var RawList = _Service.GetAllContestantRating()
                .Where(x => x.Contestant.IsActive == true)
                // .Select(x => new ContestantRating_VM { Id = x.Id, ContestantId = x.ContestantId, Rating = x.Rating, RatedDate = x.RatedDate, Contestant = x.Contestant })
                .ToList();

            var groupedResult = RawList.GroupBy(x => x.ContestantId).Select(x => x);

            foreach (var item in groupedResult)
            {
                if (FilterOperation)
                {
                    //Perform Filter 
                    var datefilter = from a in item.Select(x => x)
                                            where (a.RatedDate.Date >= Datefrom &&  a.RatedDate.Date <= Dateto) || (a.RatedDate.Date >= Datefrom || a.RatedDate.Date <= Dateto)
                                            select a;

                  
                    if (datefilter.Count()>0)
                    {
                       decimal avg = (decimal)datefilter.Sum(x => x.Rating) / datefilter.Count();
                        var obj = datefilter.FirstOrDefault(x => x.ContestantId == item.Key);

                        Returnlist.Add(new ContestantRating_VM { ContestantId = obj.ContestantId, AverageRate = avg, Contestant = obj.Contestant });
                    }

                   

                   

                   
                }
                else
                {
                    //Calculate directly 
              
                    var avg = ((decimal)item.Sum(x => x.Rating) / item.Count());

                    var obj = item.FirstOrDefault(x => x.ContestantId== item.Key);

                    Returnlist.Add(new ContestantRating_VM { ContestantId = obj.ContestantId, AverageRate = avg, Contestant = obj.Contestant });

                }

            }

            return Returnlist;

        }

        // GET: ContestantRating
        public ActionResult Index()
        {
            var list = GetAverageRating(null, null, FilterOperation: false);

            return View(list);
        }

       
        public ActionResult SearchIndex(DateTime? Datefrom, DateTime? Dateto)
        {

            var list = GetAverageRating(Datefrom,Dateto, FilterOperation: true);

           
            return View("Index", list);

        }


        [HttpPost]
        public ActionResult AddNewRating(ContestantRating obj)
        {
            bool Success = false;

            try
            {
                obj.RatedDate = DateTime.Now;
                _Service.InsertContestantRating(obj);

                Response.StatusCode = 200;
                Success = true;



            }
            catch (Exception)
            {
                Response.StatusCode = 500;

            }

            return Json(new { Result = Success });
        }

    }
}

ContestantSystem/ContestantSystem.Web/Controllers/GalleryController.cs
using ContestantSystem.Service.Contestant;
using ContestantSystem.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContestantSystem.Web.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IContestantService _Service;
        public GalleryController()
        {
            _Service = new ContestantService();
        }
        // GET: Gallery
        public ActionResult Index()
        {
            IList<Contestant_VM> VMList = _Service.GetAllContestants().Where(x=>x.IsActive==true).Select(x => new Contestant_VM().Domain_To_VM(x)).ToList();

            return View(VMList);

           
        }
    }
}

ContestantSystem/ContestantSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Amnil</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Plugin/lobibox/dist/css/lobibox.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contestant System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Contestant", "Index", "Contestant")</li>
                    <li>@Html.ActionLink("Contestant Rating", "Index", "ContestantRating")</li>
                    <li>@Html.ActionLink("Photo Gallery", "Index", "Gallery")</li>
                    <li>@Html.ActionLink("Map", "Index", "Map")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Amnil Technologies</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Plugin/lobibox/dist/js/lobibox.min.js"></script>

    <script type="text/javascript">

        var ShowError = function (type,title,message) {

            Lobibox.notify(type.toLowerCase() || 'error', {
                title: title ||'No title',
                size: 'mini',
                rounded: false,
                delayIndicator: true,
                msg: message ||'No Content provided'
            });
        }


        var stringArray = @Html.Raw(Json.Encode(TempData["Message"]));
        if (stringArray != null) {
            ShowError(stringArray[0], stringArray[1], stringArray[2]);
        }
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>